django-shop/base/urls.py
from django.urls import path, include

from base import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('', include('payment.urls', namespace='payment')),
    path('user/', include('account.urls', namespace='account')),
    path('admin/', include('dashboard.admin_urls', namespace='admin-dashboard')),
    path('admin/product/', include('product.admin_urls', namespace='admin-product')),
    path('admin/category/', include('category.admin_urls', namespace='admin-category')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-shop/payment/urls.py
from django.urls import path
from .views import *

app_name = 'payment'

urlpatterns = [
    path('stripe/payment/view', StripePaymentView.as_view(), name='stripe-payment-view'),
    path('stripe/payment/charge', stripe_payment_charge, name='stripe-payment-charge'),  # new
]

django-shop/templates/global/stripe-payment.html
{% extends 'layouts/main.html' %}
{% load static %}
{% block content %}
    <div class="flat-row-half">
        <div class="flat-checkout">
            <form action="{% url 'payment:stripe-payment-charge' %}" method="post" class="form-checkout">
                {% csrf_token %}
                <input type="hidden" value="{{ amount }}" name="amount">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8 col-md-8 col-sm-12">
                            <div class="buyer-info checkout-border">
                                <div class="bg d-flex justify-content-between">
                                    <div class="title">
                                        <a href="#">BUYER INFO</a>
                                    </div>
                                    <div class="title">
                                        <a href="#">LOGIN HERE</a>
                                    </div>
                                </div>
                                <div class="content">
                                    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                                            data-key="{{ key }}"
                                            data-description="product buy payment"
                                            data-amount={{ amount }}00
                                            data-locale="auto"></script>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}