django-shop/account/urls.py
from django.urls import path
from .views import *

app_name = 'account'

urlpatterns = [
    path('login', loginView, name='login'),
    path('registration', registration, name='registration'),
    path('logout', user_logout, name='logout'),
]

django-shop/base/urls.py
from django.urls import path, include

from base import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('', include('payment.urls', namespace='payment')),
    path('user/', include('account.urls', namespace='account')),
    path('admin/', include('dashboard.admin_urls', namespace='admin-dashboard')),
    path('admin/product/', include('product.admin_urls', namespace='admin-product')),
    path('admin/category/', include('category.admin_urls', namespace='admin-category')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-shop/dashboard/urls.py
from django.urls import path
from .views import *

app_name = 'dashboard'

urlpatterns = [
    path('', dashboard, name='index'),
    path('checkout', checkout, name='checkout'),
    path('cart', cart, name='cart'),
]

django-shop/templates/layouts/alert-message.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <div class="alert alert-success alert-dismissible">
                <button type="button" class="close close-test" data-dismiss="alert" aria-hidden="true"
                        style="position: relative !important; top: -2px !important; right: 0px !important;">×
                </button>
                <h4><i class="icon fa fa-check"></i> Alert!</h4>
                <span id="alert-message">{{ message }}</span>
            </div>
        {% elif message.tags == 'warning' %}
            <div class="alert alert-warning alert-dismissible">
                <button type="button" class="close close-test" data-dismiss="alert" aria-hidden="true"
                        style="position: relative !important; top: -2px !important; right: 0px !important;">×
                </button>
                <h4><i class="icon fa fa-check"></i> Alert!</h4>
                <span id="alert-message">{{ message }}</span>
            </div>
        {% else %}
            <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close close-test" data-dismiss="alert" aria-hidden="true"
                        style="position: relative !important; top: -2px !important; right: 0px !important;">×
                </button>
                <h4><i class="icon fa fa-check"></i> Alert!</h4>
                <span id="alert-message">{{ message }}</span>
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

django-shop/templates/layouts/footer-script.html
{% load static %}
<script src="{% static 'javascript/jquery.min.js' %}"></script>
<script src="{% static 'javascript/owl.carousel.min.js' %}"></script>
<script src="{% static 'javascript/gmap3.min.js' %}"></script>
<script src="{% static 'admin/js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCo_pcAdFNbTDCAvMwAD19oRTuEmb9M50c"></script>
<script src="{% static 'javascript/jquery-ui.js' %}"></script>
<script src="{% static 'javascript/flex-slider.min.js' %}"></script>
<script src="{% static 'javascript/jquery-fancybox.js' %}"></script>
<script src="{% static 'javascript/parallax.js' %}"></script>
<script src="{% static 'javascript/equalize.min.js' %}"></script>
<script src="{% static 'javascript/plugins.js' %}"></script>
<script src="{% static 'javascript/main.js' %}"></script>

<!-- slider -->
<script src="{% static 'rev-slider/js/jquery.themepunch.tools.min.js' %}"></script>
<script src="{% static 'rev-slider/js/jquery.themepunch.revolution.min.js' %}"></script>
<script src="{% static 'javascript/rev-slider.js' %}"></script>

<!-- Load Extensions only on Local File Systems ! The following part can be removed on Server for On Demand Loading -->
<script src="{% static 'rev-slider/js/extensions/extensionsrevolution.extension.actions.min.js' %}"></script>
<script src="{% static 'rev-slider/js/extensions/extensionsrevolution.extension.carousel.min.js' %}"></script>
<script src="{% static 'rev-slider/js/extensions/extensionsrevolution.extension.kenburn.min.js' %}"></script>
<script src="{% static 'rev-slider/js/extensions/extensionsrevolution.extension.layeranimation.min.js' %}"></script>
<script src="{% static 'rev-slider/js/extensions/extensionsrevolution.extension.migration.min.js' %}"></script>
<script src="{% static 'rev-slider/js/extensions/extensionsrevolution.extension.navigation.min.js' %}"></script>
<script src="{% static 'rev-slider/js/extensions/extensionsrevolution.extension.parallax.min.js' %}"></script>
<script src="{% static 'rev-slider/js/extensions/extensionsrevolution.extension.slideanims.min.js' %}"></script>
<script src="{% static 'rev-slider/js/extensions/extensionsrevolution.extension.video.min.js' %}"></script>
<script src="{% static 'javascript/parsley.min.js' %}"></script>

django-shop/templates/layouts/footer.html
{% load static %}
<div class="footer-wrap clearfix">
    <div class="logo-footer">
        <div class="img-footer">
            <img src="{% static 'images/logo/02.png' %}" alt="images">
        </div>
        <div class="copyright">
            © 2019 <a href="#">@24webpro</a> All Rights Reserved.
        </div>
        <ul class="social-icon">
            <li><a href="#"><i class="fab fa-skype"></i></a></li>
            <li><a href="#"><i class="fab fa-pinterest"></i></a></li>
            <li><a href="#"><i class="fab fa-twitter"></i></a></li>
            <li><a href="#"><i class="fab fa-vimeo-v"></i></a></li>
        </ul>
    </div>
    <div class="custom-serive widget">
        <div class="widget-title">Top Links</div>
        <ul class="widget-nav-menu">
            <li><a href="#">About Us</a></li>
            <li><a href="#">My Account</a></li>
            <li><a href="#">Privacy Policy</a></li>
            <li><a href="#">Terms & Conditions</a></li>
            <li><a href="#">Information</a></li>
        </ul>
    </div>
    <div class="information widget">
        <div class="widget-title">My Account</div>
        <ul class="widget-nav-menu">
            <li><a href="#">About Us</a></li>
            <li><a href="#">My Account</a></li>
            <li><a href="#">Privacy Policy</a></li>
            <li><a href="#">Terms & Conditions</a></li>
            <li><a href="#">Information</a></li>
        </ul>
    </div>
    <div class="our-terms widget">
        <div class="widget-title">Our Terms</div>
        <ul class="widget-nav-menu">
            <li><a href="#">About Us</a></li>
            <li><a href="#">Privacy Policy</a></li>
            <li><a href="#">Terms & Conditions</a></li>
            <li><a href="#">Information</a></li>
        </ul>
    </div>
    <div class="get-app">
        <div class="img-app">
            <img src="{% static 'images/footer/01.png' %}" alt="images">
        </div>
        <div class="img-payment">
            <img src="{% static 'images/footer/02.png' %}" alt="images">
        </div>
    </div>
</div>
<a id="scroll-top" class="show"></a>

django-shop/templates/layouts/header-nav.html
{% load static %}
<header id="header" class="header widget-header header-type1 cl-bl">
    <div class="nav">
        <div class="header-wrap d-flex">
            <div id="logo" class="logo d-flex align-items-center logo-customize-bg">
                <a href="{% url 'dashboard:index' %}" title="Xian"><img src="{% static 'images/logo/03.png' %}" data-width="85"
                                                       data-height="27" alt="images"
                                                       data-retina="{% static 'images/logo/03@2x.png' %}"></a>
            </div>
            <div class="header-content d-flex flex-grow-1 align-items-center flex-row justify-content-lg-start justify-content-end">
                <div class="icon-header-wrap-left d-flex justify-content-center">
                    <div class="wrap-language cl-bl">
                        <div class="language-name language-current">ENGLISH</div>
                        <div class="list-flat-chooser">
                            <ul class="select-name">
                                <li><a href="#">FRANCE</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="wcml-dropdown product wcml-currency-switcher cl-bl">
                        <div class="wcml-cs-item-toggle">USD</div>
                        <ul class="wcml-cs-submenu">
                            <li><a href="#">EUR</a></li>
                            <li><a href="#">KMF</a></li>
                        </ul>
                    </div>
                </div>
                <div class="nav-wrap d-flex justify-content-start">
                    <nav id="main-nav" class="main-nav" role="navigation">
                        <ul id="menu-main-menu" class="d-flex menu justify-content-start">
                            <li class="menu-item menu-item-has-children">
                                <a href="{% url 'dashboard:index' %}">HOME</a>
                            </li>
                            <li class="menu-item menu-item-has-children"><a href="#">PRODUCTS</a>
                                <ul class="sub-menu mega-menu cl-bl">
                                    <li class="mega-item">
                                        <h3 class="menu-title"><a href="#">ARCHIVE</a></h3>
                                        <ul>
                                            <li><a href="shop-details.html">Shop Details</a></li>
                                            <li><a href="shop-grid.html">Shop Grid</a></li>
                                            <li><a href="shop-grid-full-width.html">Shop Grid Full Width</a></li>
                                            <li><a href="shop-list.html">Shop List</a></li>
                                        </ul>
                                    </li>
                                    <li class="mega-item">
                                        <h3 class="menu-title"><a href="#">PRODUCT SINGLE</a></h3>
                                        <ul>
                                            <li><a href="shop-details-sidebar-left.html">Shop Details - Left sidebar</a>
                                            </li>
                                            <li><a href="shop-details-sidebar-right.html">Shop Details - Right
                                                sidebar</a></li>
                                            <li><a href="shop-grid-sidebar-left.html">Shop Grid - Left sidebar</a></li>
                                            <li><a href="shop-grid-sidebar-right.html">Shop Grid - Right sidebar</a>
                                            </li>
                                            <li><a href="shop-list-sidebar-left.html">Shop List - Left sidebar</a></li>
                                            <li><a href="shop-list-sidebar-right.html">Shop List - Right sidebar</a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="mega-item">
                                        <h3 class="menu-title"><a href="#">SHOP PAGES</a></h3>
                                        <ul>
                                            <li><a href="cart.html">Cart</a></li>
                                            <li><a href="checkout.html">Chekout</a></li>
                                        </ul>
                                    </li>
                                    <li class="mega-item mega-images">
                                        <h3 class="menu-title"><a href="#">CATEGORIES</a></h3>
                                        <span><img src="{% static 'images/home1/01.png' %}" alt="images"></span>
                                    </li>
                                </ul>
                            </li>
                            <li class="menu-item"><a href="#">ACCESSORIES</a></li>
                            <li class="menu-item menu-item-has-children"><a href="#">MORE +</a>
                                <ul class="sub-menu">
                                    <li class="menu-item"><a href="login.html">LOGIN</a></li>
                                    <li class="menu-item"><a href="blog.html">BLOG</a></li>
                                    <li class="menu-item"><a href="blog-details.html">BLOG DETAILS</a></li>
                                    <li class="menu-item"><a href="contact-us.html">CONTACT US</a></li>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                </div>
                <div class="icon-header-wrap-right d-flex justify-content-end">
                    <div class="header-item-wrap d-flex justify-content-end">
                        <div class="indicator indicator-trigger-click">
                            <a class="icon icon-header-search indicator_button" href="#"><i
                                    class="fal fa-search"></i></a>
                            <form action="#" class="search-header-hide">
                                <input type="search" class="search-product" placeholder="Enter your keyword">
                            </form>
                        </div>
                        {% if not user.is_authenticated or user.roles.is_admin %}
                            <a class="icon icon-header-user" href="{% url 'account:login' %}"><i class="fal fa-user-alt"></i></a>
                        {% else %}
                            <a class="icon icon-header-user" href="{% url 'account:logout' %}"><i class="fal fa-sign-out"></i></a>
                        {% endif %}
                        <div class="indicator indicator-trigger-click">
                            <a class="icon icon-header-wishlist indicator_button" href="#"><i class="fal fa-heart"></i></a>
                            <div class="wishlist-hide">
                                <div class="wishlist-hide-wrap">
                                    <ul>
                                        <li class="item d-flex">
                                            <div class="thumnail">
                                                <img src="{% static 'images/shop/55.png' %}" alt="images">
                                            </div>
                                            <div class="summary">
                                                <p>Furniture</p>
                                                <a href="#" class="item-name">Stool - solid</a>
                                                <div class="item-price">$999</div>
                                            </div>
                                        </li>
                                        <li class="item d-flex">
                                            <div class="thumnail">
                                                <img src="{% static 'images/shop/56.png' %}" alt="images">
                                            </div>
                                            <div class="summary">
                                                <p>Furniture</p>
                                                <a href="#" class="item-name">Lorem Ipsum</a>
                                                <div class="item-price">$999</div>
                                            </div>
                                        </li>
                                    </ul>
                                    <div class="wishlist-buttons">
                                        <a href="#" class="hv-bounce-bl">WISHLIST</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="indicator indicator-trigger-click">
                            <a class="icon icon-header-bag indicator_button" href="#"><i
                                    class="fal fa-shopping-bag"></i>
                                <span class="count-cart cl-bl">2</span>
                            </a>
                            <div class="mini-cart">
                                <div class="mini-cart-wrap">
                                    <ul>
                                        <li class="item d-flex">
                                            <div class="thumnail">
                                                <img src="{% static 'images/shop/55.png' %}" alt="images">
                                            </div>
                                            <div class="summary">
                                                <p>Furniture</p>
                                                <a href="#" class="item-name">Stool - solid</a>
                                                <div class="item-price">$999</div>
                                            </div>
                                        </li>
                                        <li class="item d-flex">
                                            <div class="thumnail">
                                                <img src="{% static 'images/shop/56.png' %}" alt="images">
                                            </div>
                                            <div class="summary">
                                                <p>Furniture</p>
                                                <a href="#" class="item-name">Lorem Ipsum</a>
                                                <div class="item-price">$999</div>
                                            </div>
                                        </li>
                                    </ul>
                                    <div class="mini-cart-total text-right">
                                        <p>
                                            <span>SUB TOTAL:</span>
                                            <span class="total">$1810.00</span>
                                        </p>
                                        <p>
                                            <span>TOTAL:</span>
                                            <span class="total">$1810.00</span>
                                        </p>
                                    </div>
                                    <div class="mini-cart-buttons">
                                        <a href="{% url 'dashboard:cart' %}" class="btn-view-cart hv-bounce-bl">VIEW CART</a>
                                        <a href="{% url 'dashboard:checkout' %}" class="btn-checkout hv-bounce-bl">CHECKOUT</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div dir="rtl" class="menu-btn d-flex justify-content-lg-end">
                    <div class="mobile-header__menu-button">
                        <div class="line line-1"></div>
                        <div class="line line-2"></div>
                        <div class="line line-3"></div>
                        <div class="line line-4"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

django-shop/templates/layouts/header-style.html
{% load static %}
<link rel="stylesheet" href="{% static 'stylesheet/bootstrap.css' %}">

<!-- Template Style-->
<link rel="stylesheet" href="{% static 'stylesheet/all.css' %}">
<link rel="stylesheet" href="{% static 'stylesheet/animate.css' %}">
<link rel="stylesheet" href="{% static 'stylesheet/style.css' %}">
<link rel="stylesheet" href="{% static 'stylesheet/shortcodes.css' %}">
<link rel="stylesheet" href="{% static 'stylesheet/mobile-menu.css' %}">
<link rel="stylesheet" href="{% static 'stylesheet/responsive.css' %}">
<link rel="stylesheet" href="{% static 'stylesheet/jquery-ui.css' %}">
<link rel="stylesheet" href="{% static 'stylesheet/flexslider.css' %}">
<link rel="stylesheet" href="{% static 'stylesheet/owl.theme.default.min.css' %}">
<link rel="stylesheet" href="{% static 'stylesheet/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'rev-slider/css/layers.css' %}">
<link rel="stylesheet" href="{% static 'rev-slider/css/navigation.css' %}">
<link rel="stylesheet" href="{% static 'rev-slider/css/settings.css' %}">
<link rel="stylesheet" href="{% static 'stylesheet/jquery-fancybox.css' %}">

<link rel="icon" type="image/png" sizes="96x96" href="{% static 'admin/img/favicon.ico' %}">
<link rel="stylesheet" href="{% static 'stylesheet/custom.css' %}">

django-shop/templates/layouts/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ESHOP</title>

    <!-- Mobile Specific Metas-->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Bootstrap-->
    {% include 'layouts/header-style.html' %}
</head>

<body>
<div id="loading-overlay">
    <div class="loader"></div>
</div>
<div class="bg-bordcuct-2">
    <!-- header -->
    {% include 'layouts/header-nav.html' %}
</div><!-- bg-bordcuct -->
{#<section class="flat-slider clearfix">#}
{#    {% include 'layouts/rev-slider.html' %}#}
{#</section><!-- flat-slider -->#}
{% block content %} {% endblock content %}

<footer id="footer" class="footer footer-type2 footer-home">
    {% include 'layouts/footer.html' %}
</footer><!-- footer -->
<div class="mobile-menu">
    {% include 'layouts/mobile-menu.html' %}
</div><!-- mobile-menu -->
<!-- footer script -->
{% include 'layouts/footer-script.html' %}
{% block script %}{% endblock %}
</body>
</html>